embed_assets: on

javascripts:
  common:
    - public/javascripts/jquery-1.4.4.min.js
    - public/javascripts/rails.js

stylesheets:
  public:
    - public/stylesheets/reset.css
    - public/stylesheets/application.css
